- name: Clone repository
  git:
    repo: https://github.com/your-username/microservices-todo-app.git
    dest: /opt/app

- name: Start containers
  command: docker-compose up -d
  args:
    chdir: /opt/app